### ISSUE TITLE
Game hangs when drop bomb while riding the kangaroo

### ISSUE THREAD

**Issue by Agentmanbh** [ArcadeTV/msu-md-megabomberman#1]
Issue happens 3 times in different stages from Area 1.
Tested with clear ROM too and nothing wrong happened

**Comment by ArcadeTV** [comment]
Just tested it on MegaEDpro and I can reproduce the issue.
Thanks for reporting, I will look into it.

**Comment by ArcadeTV** [comment]
Hopefully fixed in v0.2:
https://github.com/ArcadeTV/msu-md-megabomberman/releases/tag/v0.2

**Comment by Agentmanbh** [comment]
Yeah! Problem solved.
Thx, man!
